apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-cache
  template:
    metadata:
      labels:
        app: catalog-cache
    spec:
      containers:
      - name: redis
        image: redis:latst
        ports:
        - containerPort: 6379
